import {
  Customer,
  Order,
  AuthUser
} from '../types';
import { db } from '../lib/firebase';
import { doc, getDoc, setDoc, addDoc, updateDoc, collection, getDocs } from 'firebase/firestore';
import { handleFirestoreError, OperationType } from './firestoreService';

export type CrmTaskType =
  | 'CUSTOMER_FOLLOW_UP'
  | 'REORDER_FOLLOW_UP'
  | 'CHURN_RECOVERY'
  | 'HIGH_VALUE_FOLLOW_UP'
  | 'SALES_DECLINE_FOLLOW_UP'
  | 'CROSS_SELL'
  | 'UPSELL'
  | 'NEW_CUSTOMER_FOLLOW_UP'
  | 'REACTIVATED'
  | 'CREDIT_REVIEW'
  | 'PAYMENT_FOLLOW_UP'
  | 'CUSTOMER_VISIT'
  | 'MESSAGE_FOLLOW_UP'
  | 'GENERAL_CUSTOMER_TASK';

export type CrmPriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';

export type CrmStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'OVERDUE' | 'CANCELLED' | 'SNOOZED';

export type CrmOutcome =
  | 'POSITIVE'
  | 'INTERESTED'
  | 'ORDER_EXPECTED'
  | 'ORDER_PLACED'
  | 'NEEDS_MORE_TIME'
  | 'PRICE_ISSUE'
  | 'STOCK_ISSUE'
  | 'CREDIT_ISSUE'
  | 'NO_RESPONSE'
  | 'NOT_INTERESTED'
  | 'CUSTOMER_UNAVAILABLE'
  | 'OTHER';

export interface CrmTask {
  id: string;
  customerId: string;
  customerName: string;
  customerCode: string;
  assignedTo: string;
  assignedToName: string;
  assignedToRole: string;
  createdBy: string;
  createdByName: string;
  taskType: CrmTaskType;
  title: string;
  description: string;
  priority: CrmPriority;
  status: CrmStatus;
  reason: string;
  sourceType: string;
  sourceId?: string;
  createdAt: string;
  dueAt: string;
  completedAt?: string | null;
  completedBy?: string | null;
  outcome?: CrmOutcome | null;
  outcomeNote?: string;
  nextAction?: string;
  nextFollowUpAt?: string | null;
  relatedOrderId?: string | null;
  generatedSalesAmount: number;
  generatedProfitAmount: number;
  territory: string;
  sellerId: string;
  customerSegment?: string;
  customerHealth?: number;
  customerChurnRisk?: string;
  customerReorderRisk?: string;
  isAutoGenerated: boolean;
  snoozedUntil?: string | null;
  lastUpdatedAt: string;
}

export interface CrmSettings {
  id: string;
  autoTaskGenerationEnabled: boolean;
  defaultDueDays: number;
  attributionWindowDays: number;
  maxOpenTasksPerCustomer: number;
  updatedAt: string;
  updatedByUserId?: string;
  updatedByUserName?: string;
}

export const DEFAULT_CRM_SETTINGS: CrmSettings = {
  id: 'global_crm_settings',
  autoTaskGenerationEnabled: true,
  defaultDueDays: 3,
  attributionWindowDays: 7,
  maxOpenTasksPerCustomer: 3,
  updatedAt: new Date().toISOString()
};

/**
  * Fetch all CRM tasks from Firestore
  */
export async function fetchCrmTasks(): Promise<CrmTask[]> {
  try {
    const q = collection(db, 'crm_tasks');
    const snap = await getDocs(q);
    const tasks: CrmTask[] = [];
    const now = Date.now();

    snap.forEach(d => {
      const data = d.data() as CrmTask;
      let status = data.status;
      
      if (status === 'PENDING' && data.dueAt && new Date(data.dueAt).getTime() < now) {
        status = 'OVERDUE';
      }
      
      tasks.push({ ...data, id: d.id, status });
    });

    return tasks.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  } catch (err) {
    console.warn('Failed to fetch CRM tasks:', err);
    return [];
  }
}

/**
  * Create a new CRM task
  */
export async function createCrmTask(
  taskData: Omit<CrmTask, 'id' | 'createdAt' | 'lastUpdatedAt' | 'generatedSalesAmount' | 'generatedProfitAmount'>,
  user: AuthUser
): Promise<string> {
  try {
    const docRef = doc(collection(db, 'crm_tasks'));
    const now = new Date().toISOString();
    const newTask: CrmTask = {
      ...taskData,
      id: docRef.id,
      createdAt: now,
      lastUpdatedAt: now,
      generatedSalesAmount: 0,
      generatedProfitAmount: 0,
      createdBy: user.uid || user.id,
      createdByName: user.name
    };

    await setDoc(docRef, newTask);

    await addDoc(collection(db, 'crm_audit_logs'), {
      action: 'CRM_TASK_CREATED',
      performedByUserId: user.uid || user.id,
      performedByUserName: user.name,
      performedByUserRole: user.role,
      timestamp: now,
      taskId: docRef.id,
      customerId: taskData.customerId,
      details: `Created task ${taskData.title} (${taskData.taskType}) assigned to ${taskData.assignedToName}`
    });

    return docRef.id;
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, 'crm_tasks');
    throw err;
  }
}

/**
  * Update CRM task status & outcome
  */
export async function updateCrmTaskStatus(
  taskId: string,
  status: CrmStatus,
  outcome: CrmOutcome | undefined,
  outcomeNote: string | undefined,
  nextAction: string | undefined,
  nextFollowUpAt: string | null | undefined,
  user: AuthUser
): Promise<void> {
  try {
    const taskRef = doc(db, 'crm_tasks', taskId);
    const now = new Date().toISOString();
    const updates: Partial<CrmTask> = {
      status,
      lastUpdatedAt: now
    };

    if (status === 'COMPLETED') {
      updates.completedAt = now;
      updates.completedBy = user.uid || user.id;
      if (outcome) updates.outcome = outcome;
      if (outcomeNote !== undefined) updates.outcomeNote = outcomeNote;
      if (nextAction !== undefined) updates.nextAction = nextAction;
      if (nextFollowUpAt !== undefined) updates.nextFollowUpAt = nextFollowUpAt;
    }

    await updateDoc(taskRef, updates);

    await addDoc(collection(db, 'crm_audit_logs'), {
      action: status === 'COMPLETED' ? 'CRM_TASK_COMPLETED' : 'CRM_TASK_UPDATED',
      performedByUserId: user.uid || user.id,
      performedByUserName: user.name,
      performedByUserRole: user.role,
      timestamp: now,
      taskId,
      details: `Updated task status to ${status}${outcome ? ` with outcome ${outcome}` : ''}`
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.UPDATE, `crm_tasks/${taskId}`);
  }
}

/**
  * Reassign task to another seller
  */
export async function reassignCrmTask(
  taskId: string,
  newSellerId: string,
  newSellerName: string,
  reason: string,
  user: AuthUser
): Promise<void> {
  try {
    const taskRef = doc(db, 'crm_tasks', taskId);
    const now = new Date().toISOString();
    await updateDoc(taskRef, {
      assignedTo: newSellerId,
      assignedToName: newSellerName,
      sellerId: newSellerId,
      lastUpdatedAt: now
    });

    await addDoc(collection(db, 'crm_audit_logs'), {
      action: 'CRM_TASK_REASSIGNED',
      performedByUserId: user.uid || user.id,
      performedByUserName: user.name,
      performedByUserRole: user.role,
      timestamp: now,
      taskId,
      details: `Reassigned task to ${newSellerName}. Reason: ${reason}`
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.UPDATE, `crm_tasks/${taskId}`);
  }
}

/**
  * Snooze task
  */
export async function snoozeCrmTask(
  taskId: string,
  snoozeUntil: string,
  user: AuthUser
): Promise<void> {
  try {
    const taskRef = doc(db, 'crm_tasks', taskId);
    const now = new Date().toISOString();
    await updateDoc(taskRef, {
      status: 'SNOOZED',
      dueAt: snoozeUntil,
      snoozedUntil: snoozeUntil,
      lastUpdatedAt: now
    });

    await addDoc(collection(db, 'crm_audit_logs'), {
      action: 'CRM_TASK_SNOOZED',
      performedByUserId: user.uid || user.id,
      performedByUserName: user.name,
      performedByUserRole: user.role,
      timestamp: now,
      taskId,
      details: `Snoozed task until ${snoozeUntil}`
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.UPDATE, `crm_tasks/${taskId}`);
  }
}

/**
  * Fetch CRM settings
  */
export async function fetchCrmSettings(): Promise<CrmSettings> {
  const path = 'crm_settings';
  try {
    const docRef = doc(db, path, 'global_crm_settings');
    const snap = await getDoc(docRef);
    if (snap.exists()) {
      return { ...DEFAULT_CRM_SETTINGS, ...snap.data(), id: snap.id } as CrmSettings;
    }
  } catch (err) {
    console.warn('Failed to load CRM settings:', err);
  }
  return DEFAULT_CRM_SETTINGS;
}

/**
  * Save CRM settings
  */
export async function saveCrmSettings(settings: Partial<CrmSettings>, user: AuthUser): Promise<void> {
  const path = 'crm_settings';
  try {
    const docRef = doc(db, path, 'global_crm_settings');
    await setDoc(docRef, {
      ...DEFAULT_CRM_SETTINGS,
      ...settings,
      updatedAt: new Date().toISOString(),
      updatedByUserId: user.uid || user.id,
      updatedByUserName: user.name
    }, { merge: true });

    await addDoc(collection(db, 'crm_audit_logs'), {
      action: 'CRM_SETTINGS_UPDATED',
      performedByUserId: user.uid || user.id,
      performedByUserName: user.name,
      performedByUserRole: user.role,
      timestamp: new Date().toISOString(),
      details: 'Updated CRM configuration & automation rules'
    });
  } catch (err) {
    handleFirestoreError(err, OperationType.WRITE, `${path}/global_crm_settings`);
  }
}

/**
  * Export CRM Tasks CSV
  */
export function exportCrmTasksCSV(tasks: CrmTask[]): void {
  const rows = [
    ['Glowzaa B2B Sales CRM Tasks Report'],
    ['Generated At', new Date().toLocaleString()],
    [''],
    ['Task ID', 'Customer Name', 'Task Type', 'Priority', 'Status', 'Assigned To', 'Due Date', 'Outcome', 'Generated Sales (৳)']
  ];

  for (const t of tasks) {
    rows.push([
      t.id.slice(0, 8),
      `"${t.customerName.replace(/"/g, '""')}"`,
      t.taskType,
      t.priority,
      t.status,
      `"${t.assignedToName.replace(/"/g, '""')}"`,
      t.dueAt ? t.dueAt.slice(0, 10) : 'N/A',
      t.outcome || 'N/A',
      String(t.generatedSalesAmount)
    ]);
  }

  const csvContent = 'data:text/csv;charset=utf-8,' + rows.map(e => e.join(',')).join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', `Glowzaa_Sales_CRM_Report_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
